/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cleartraders.webadmin.controller.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

import com.cleartraders.common.util.tools.CommonTools;

/** 
 * MyEclipse Struts
 * Creation date: 02-25-2009
 * 
 * XDoclet definition:
 * @struts.form name="adminLoginForm"
 */
public class AdminLoginForm extends ActionForm
{
    /*
     * Generated Methods
     */
    
    /** username property */
    private String username;

    /** password property */
    private String password;

    /**
     * 
     */
    private static final long serialVersionUID = -993234213587795764L;

    /** 
     * Method validate
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping,
            HttpServletRequest request)
    {
        ActionErrors errors = new ActionErrors();
        
        if(null == username || username.length() < 1)
        {
            errors.add("username", new ActionMessage("login.no.username.error"));
        }
        else
        {
            username = CommonTools.filteDangerString(username);
        }
        
        if(null == password || password.length() < 1)
        {
            errors.add("password", new ActionMessage("login.no.password.error"));
        }
        else
        {
            password = CommonTools.filteDangerString(password);
        }
        
        return errors;
    }

    /** 
     * Method reset
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request)
    {
        // TODO Auto-generated method stub
    }

    public String getPassword()
    {
        return password;
    }

    public void setPassword(String password)
    {
        this.password = password;
    }

    public String getUsername()
    {
        return username;
    }

    public void setUsername(String username)
    {
        this.username = username;
    }
}
