/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cleartraders.webadmin.controller.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

import com.cleartraders.common.util.tools.CommonTools;

/** 
 * MyEclipse Struts
 * Creation date: 03-13-2009
 * 
 * XDoclet definition:
 * @struts.form name="resetMemberPWDForm"
 */
public class ResetMemberPWDForm extends ActionForm
{
    /*
     * Generated Methods
     */

    /**
     * 
     */
    private static final long serialVersionUID = 5671907214925595083L;
    private String reset_pwd_member_id="";
    private String reset_new_pwd="";
    

    public String getReset_new_pwd()
    {
        return reset_new_pwd;
    }

    public void setReset_new_pwd(String reset_new_pwd)
    {
        this.reset_new_pwd = reset_new_pwd;
    }

    public String getReset_pwd_member_id()
    {
        return reset_pwd_member_id;
    }

    public void setReset_pwd_member_id(String reset_pwd_member_id)
    {
        this.reset_pwd_member_id = reset_pwd_member_id;
    }

    /** 
     * Method validate
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping,
            HttpServletRequest request)
    {
        ActionErrors errors = new ActionErrors();
        
        if(this.reset_pwd_member_id == null || this.reset_pwd_member_id.trim().length() == 0)
        {
            errors.add("error", new ActionMessage("member.reset.pwd.request.data.error"));
        }
        else if(this.reset_pwd_member_id.trim().length() > 100)
        {
            errors.add("error", new ActionMessage("member.reset.pwd.request.data.error"));
        }
        else
        {
            this.reset_pwd_member_id = CommonTools.filteDangerString(reset_pwd_member_id);
        }
        
        if(this.reset_new_pwd == null || this.reset_new_pwd.trim().length() == 0)
        {
            errors.add("member_name", new ActionMessage("member.reset.pwd.request.data.error"));
        }
        else if(this.reset_new_pwd.trim().length() > 100)
        {
            errors.add("member_name", new ActionMessage("member.reset.pwd.request.data.error"));
        }
        else
        {
            this.reset_new_pwd = CommonTools.filteDangerString(reset_new_pwd);
        }
        
        return errors;
    }

    /** 
     * Method reset
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request)
    {
        // TODO Auto-generated method stub
    }
}
