/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cleartraders.webapp.controller.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 05-07-2010
 * 
 * XDoclet definition:
 * @struts.form name="addSignalForm"
 */
public class AddSignalForm extends ActionForm
{
    /*
     * Generated fields
     */

    /** time_frame_id property */
    private String time_frame_id;

    /** market_id property */
    private String market_id;

    /** indicator_id property */
    private String indicator_id;

    /** alert_type property */
    private String alert_type;

    /*
     * Generated Methods
     */

    /** 
     * Method validate
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping, HttpServletRequest request)
    {
        // TODO Auto-generated method stub
        return null;
    }

    /** 
     * Method reset
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request)
    {
        // TODO Auto-generated method stub
    }

    /** 
     * Returns the time_frame_id.
     * @return String
     */
    public String getTime_frame_id()
    {
        return time_frame_id;
    }

    /** 
     * Set the time_frame_id.
     * @param time_frame_id The time_frame_id to set
     */
    public void setTime_frame_id(String time_frame_id)
    {
        this.time_frame_id = time_frame_id;
    }

    /** 
     * Returns the market_id.
     * @return String
     */
    public String getMarket_id()
    {
        return market_id;
    }

    /** 
     * Set the market_id.
     * @param market_id The market_id to set
     */
    public void setMarket_id(String market_id)
    {
        this.market_id = market_id;
    }

    /** 
     * Returns the indicator_id.
     * @return String
     */
    public String getIndicator_id()
    {
        return indicator_id;
    }

    /** 
     * Set the indicator_id.
     * @param indicator_id The indicator_id to set
     */
    public void setIndicator_id(String indicator_id)
    {
        this.indicator_id = indicator_id;
    }

    /** 
     * Returns the alert_type.
     * @return String
     */
    public String getAlert_type()
    {
        return alert_type;
    }

    /** 
     * Set the alert_type.
     * @param alert_type The alert_type to set
     */
    public void setAlert_type(String alert_type)
    {
        this.alert_type = alert_type;
    }
}
