/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cleartraders.webapp.controller.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

import com.cleartraders.common.util.tools.CommonTools;

/** 
 * MyEclipse Struts
 * Creation date: 03-08-2009
 * 
 * XDoclet definition:
 * @struts.form name="changeSubscriptionForm"
 */
public class ChangeSubscriptionForm extends ActionForm
{
    /*
     * Generated Methods
     */

    /**
     * 
     */
    private static final long serialVersionUID = 4195533069068146775L;
    
    private String subscrible_product="";
    private String username="";
    private String password="";
    private String security_code="";

    public String getPassword()
    {
        return password;
    }

    public void setPassword(String password)
    {
        this.password = password;
    }

    public String getSecurity_code()
    {
        return security_code;
    }

    public void setSecurity_code(String security_code)
    {
        this.security_code = security_code;
    }

    public String getSubscrible_product()
    {
        return subscrible_product;
    }

    public void setSubscrible_product(String subscrible_product)
    {
        this.subscrible_product = subscrible_product;
    }

    public String getUsername()
    {
        return username;
    }

    public void setUsername(String username)
    {
        this.username = username;
    }

    /** 
     * Method validate
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping,
            HttpServletRequest request)
    {
        ActionErrors errors = new ActionErrors();
        
        if(this.subscrible_product == null || this.subscrible_product.trim().length() == 0 )
        {
            errors.add("subscrible_product", new ActionMessage("upgrade.membership.no.product.type.error"));
        }
        else if(this.subscrible_product.trim().length() > 100)
        {
            errors.add("subscrible_product", new ActionMessage("upgrade.membership.product.type.too.long.error"));
        }
        else
        {
            subscrible_product = CommonTools.filteDangerString(subscrible_product);
        }
        
        if(this.username == null || this.username.trim().length() == 0)
        {
            errors.add("username", new ActionMessage("upgrade.membership.no.username.error"));
        }
        else if(this.username.trim().length() > 100)
        {
            errors.add("username", new ActionMessage("upgrade.membership.username.too.long.error"));
        }
        else
        {
            this.username = CommonTools.filteDangerString(username);
        }
        
        if(this.password == null || this.password.trim().length() == 0)
        {
            errors.add("password", new ActionMessage("upgrade.membership.no.password.error"));
        }
        else if(this.password.trim().length() > 100)
        {
            errors.add("password", new ActionMessage("upgrade.membership.password.too.long.error"));
        }
        else
        {
            this.password = CommonTools.filteDangerString(password);
        }
        
        if(this.security_code == null || this.security_code.trim().length() == 0)
        {
            errors.add("security_code", new ActionMessage("upgrade.membership.no.security.code.error"));
        }
        else if(this.security_code.trim().length() > 100)
        {
            errors.add("security_code", new ActionMessage("upgrade.membership.security.code.too.long.error"));
        }
        else
        {
            this.security_code = CommonTools.filteDangerString(security_code);
        }
                
        return errors; 
    }

    /** 
     * Method reset
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request)
    {
        // TODO Auto-generated method stub
    }
}
