/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cleartraders.webapp.controller.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.cleartraders.common.util.tools.CommonTools;

/** 
 * MyEclipse Struts
 * Creation date: 12-13-2008
 * 
 * XDoclet definition:
 * @struts.form name="ChangeAutoTradeStatusForm"
 */
public class ChangeAutoTradeStatusForm extends ActionForm
{
    /*
     * Generated fields
     */

    /**
     * 
     */
    private static final long serialVersionUID = -1516456083513115280L;
    /** auto_trade_status property */
    private String operation_type;

    /*
     * Generated Methods
     */

    /** 
     * Method validate
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping,
            HttpServletRequest request)
    {
        if(null == operation_type)
        {
            operation_type = "1";
        }
        else
        {
            operation_type = CommonTools.filteDangerString(operation_type);
        }
        
        return null;
    }

    /** 
     * Method reset
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request)
    {
        // TODO Auto-generated method stub
    }

    /** 
     * Returns the auto_trade_status.
     * @return String
     */
    public String getOperation_type()
    {
        return operation_type;
    }

    /** 
     * Set the auto_trade_status.
     * @param auto_trade_status The auto_trade_status to set
     */
    public void setOperation_type(String operation_type)
    {
        this.operation_type = operation_type;
    }
}
