/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cleartraders.webapp.controller.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-04-2010
 * 
 * XDoclet definition:
 * @struts.form name="changeAlertForm"
 */
public class ChangeAlertForm extends ActionForm
{
    /*
     * Generated fields
     */

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /** period_id property */
    private String period_id;

    /** market_id property */
    private String market_id;

    /** alert_type property */
    private String alert_type;

    /** strategy_id property */
    private String strategy_id;

    /*
     * Generated Methods
     */

    /** 
     * Method validate
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping, HttpServletRequest request)
    {
        // TODO Auto-generated method stub
        return null;
    }

    /** 
     * Method reset
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request)
    {
        // TODO Auto-generated method stub
    }

    /** 
     * Returns the period_id.
     * @return String
     */
    public String getPeriod_id()
    {
        return period_id;
    }

    /** 
     * Set the period_id.
     * @param period_id The period_id to set
     */
    public void setPeriod_id(String period_id)
    {
        this.period_id = period_id;
    }

    /** 
     * Returns the market_id.
     * @return String
     */
    public String getMarket_id()
    {
        return market_id;
    }

    /** 
     * Set the market_id.
     * @param market_id The market_id to set
     */
    public void setMarket_id(String market_id)
    {
        this.market_id = market_id;
    }

    /** 
     * Returns the alert_type.
     * @return String
     */
    public String getAlert_type()
    {
        return alert_type;
    }

    /** 
     * Set the alert_type.
     * @param alert_type The alert_type to set
     */
    public void setAlert_type(String alert_type)
    {
        this.alert_type = alert_type;
    }

    /** 
     * Returns the strategy_id.
     * @return String
     */
    public String getStrategy_id()
    {
        return strategy_id;
    }

    /** 
     * Set the strategy_id.
     * @param strategy_id The strategy_id to set
     */
    public void setStrategy_id(String strategy_id)
    {
        this.strategy_id = strategy_id;
    }
}
