/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cleartraders.webapp.controller.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

import com.cleartraders.common.util.tools.CommonTools;

/** 
 * MyEclipse Struts
 * Creation date: 02-24-2009
 * 
 * XDoclet definition:
 * @struts.form name="changeMembershipForm"
 */
public class ChangeMembershipForm extends ActionForm
{
    /*
     * Generated Methods
     */
    
    private String member_plan;

    /**
     * 
     */
    private static final long serialVersionUID = 4433347954304271906L;

    /** 
     * Method validate
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping,
            HttpServletRequest request)
    {
        ActionErrors errors = new ActionErrors();
        
        if(null == member_plan || member_plan.length() < 1)
        {
            errors.add("current_membership", new ActionMessage("changepwd.no.current.membership.error"));
        }
        else
        {
            member_plan = CommonTools.filteDangerString(member_plan);
        }
        
        return errors;
    }

    /** 
     * Method reset
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request)
    {
    }

    public String getMember_plan()
    {
        return member_plan;
    }

    public void setMember_plan(String member_plan)
    {
        this.member_plan = member_plan;
    }
}
