/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cleartraders.webapp.controller.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.cleartraders.common.util.tools.CommonTools;

/** 
 * MyEclipse Struts
 * Creation date: 09-23-2008
 * 
 * XDoclet definition:
 * @struts.form name="ContactsForm"
 */
public class ContactsForm extends ActionForm
{
    private static final long serialVersionUID = -1488192829881700986L;

    /** email property */
    private String email;
    
    /** mobile property */
    private String mobile;

    /** first_name property */
    private String first_name;
    
    /** last_name property */
    private String last_name;

    /** country property */
    private String country;

    /** time_zone property */
    private String time_zone;
    
    /** password property */
    private String password;
    
    /** confirmpassword property */
    private String confirmpassword;
    
    /*
     * Generated Methods
     */

    /** 
     * Method validate
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping,
            HttpServletRequest request)
    {
        if(email != null)
        {
            email = CommonTools.filteDangerString(email);
        }
        
        if(mobile != null)
        {
            mobile = CommonTools.filteDangerString(mobile);
        }
        
        if(first_name != null)
        {
            first_name = CommonTools.filteDangerString(first_name);
        }
        
        if(last_name != null)
        {
            last_name = CommonTools.filteDangerString(last_name);
        }
                
        if(country != null)
        {
            country = CommonTools.filteDangerString(country);
        }
        
        if(time_zone != null)
        {
            time_zone = CommonTools.filteDangerString(time_zone);
        }
        
        if(password != null)
        {
            password = CommonTools.filteDangerString(password);
        }
        
        if(confirmpassword != null)
        {
            confirmpassword = CommonTools.filteDangerString(confirmpassword);
        }
        
        return null;
    }

    /** 
     * Method reset
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request)
    {
        // TODO Auto-generated method stub
    }

    public String getConfirmpassword()
    {
        return confirmpassword;
    }

    public void setConfirmpassword(String confirmpassword)
    {
        this.confirmpassword = confirmpassword;
    }

    public String getPassword()
    {
        return password;
    }

    public void setPassword(String password)
    {
        this.password = password;
    }

    public String getTime_zone()
    {
        return time_zone;
    }

    public void setTime_zone(String time_zone)
    {
        this.time_zone = time_zone;
    }
    
    /** 
     * Returns the first_name.
     * @return String
     */
    public String getFirst_name()
    {
        return first_name;
    }

    /** 
     * Set the first_name.
     * @param first_name The first_name to set
     */
    public void setFirst_name(String first_name)
    {
        this.first_name = first_name;
    }

    /** 
     * Returns the email.
     * @return String
     */
    public String getEmail()
    {
        return email;
    }

    /** 
     * Set the email.
     * @param email The email to set
     */
    public void setEmail(String email)
    {
        this.email = email;
    }

    /** 
     * Returns the last_name.
     * @return String
     */
    public String getLast_name()
    {
        return last_name;
    }

    /** 
     * Set the last_name.
     * @param last_name The last_name to set
     */
    public void setLast_name(String last_name)
    {
        this.last_name = last_name;
    }

    /** 
     * Returns the country.
     * @return String
     */
    public String getCountry()
    {
        return country;
    }

    /** 
     * Set the country.
     * @param country The country to set
     */
    public void setCountry(String country)
    {
        this.country = country;
    }

    /** 
     * Returns the mobile.
     * @return String
     */
    public String getMobile()
    {
        return mobile;
    }

    /** 
     * Set the mobile.
     * @param mobile The mobile to set
     */
    public void setMobile(String mobile)
    {
        this.mobile = mobile;
    }
}
