/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cleartraders.webapp.controller.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 05-11-2010
 * 
 * XDoclet definition:
 * @struts.form name="delSignalForm"
 */
public class DelSignalForm extends ActionForm
{    
    private static final long serialVersionUID = 1L;
    /** subscription_id property */
    private String subscription_id;

    /*
     * Generated Methods
     */

    /** 
     * Method validate
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping, HttpServletRequest request)
    {
        // TODO Auto-generated method stub
        return null;
    }

    /** 
     * Method reset
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request)
    {
        // TODO Auto-generated method stub
    }

    /** 
     * Returns the subscription_id.
     * @return String
     */
    public String getSubscription_id()
    {
        return subscription_id;
    }

    /** 
     * Set the subscription_id.
     * @param subscription_id The subscription_id to set
     */
    public void setSubscription_id(String subscription_id)
    {
        this.subscription_id = subscription_id;
    }
}
