/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cleartraders.webapp.controller.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

import com.cleartraders.common.util.tools.CommonTools;

/** 
 * MyEclipse Struts
 * Creation date: 03-08-2009
 * 
 * XDoclet definition:
 * @struts.form name="contactUsForm"
 */
public class EnquiryForm extends ActionForm
{
    /*
     * Generated Methods
     */

    /**
     * 
     */
    private static final long serialVersionUID = -8464788515975434214L;
    
    private String enquiry_type = "";
    private String first_name = "";
    private String last_name = "";
    private String email = "";
    private String enquiry = "";
    private String security_code = "";

    public String getEmail()
    {
        return email;
    }

    public void setEmail(String email)
    {
        this.email = email;
    }

    public String getEnquiry()
    {
        return enquiry;
    }

    public void setEnquiry(String enquiry)
    {
        this.enquiry = enquiry;
    }

    public String getEnquiry_type()
    {
        return enquiry_type;
    }

    public void setEnquiry_type(String enquiry_type)
    {
        this.enquiry_type = enquiry_type;
    }

    public String getFirst_name()
    {
        return first_name;
    }

    public void setFirst_name(String first_name)
    {
        this.first_name = first_name;
    }

    public String getLast_name()
    {
        return last_name;
    }

    public void setLast_name(String last_name)
    {
        this.last_name = last_name;
    }

    public String getSecurity_code()
    {
        return security_code;
    }

    public void setSecurity_code(String security_code)
    {
        this.security_code = security_code;
    }

    /** 
     * Method validate
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping,
            HttpServletRequest request)
    {
        ActionErrors errors = new ActionErrors();
        
        if(this.enquiry_type == null || this.enquiry_type.trim().length() == 0 )
        {
            errors.add("enquiry_type", new ActionMessage("enquiry.type.error"));
        }
        else if(this.enquiry_type.trim().length() > 100)
        {
            errors.add("enquiry_type", new ActionMessage("enquiry.type.too.long.error"));
        }
        else
        {
            enquiry_type = CommonTools.filteDangerString(enquiry_type);
        }
        
        if(this.first_name == null || this.first_name.trim().length() == 0)
        {
            errors.add("first_name", new ActionMessage("enquiry.no.firstname.error"));
        }
        else if(this.first_name.trim().length() > 100)
        {
            errors.add("first_name", new ActionMessage("enquiry.firstname.too.long.error"));
        }
        else
        {
            this.first_name = CommonTools.filteDangerString(first_name);
        }
        
        if(this.last_name == null || this.last_name.trim().length() == 0)
        {
            errors.add("last_name", new ActionMessage("enquiry.no.lastname.error"));
        }
        else if(this.last_name.trim().length() > 100)
        {
            errors.add("last_name", new ActionMessage("enquiry.lastname.too.long.error"));
        }
        else
        {
            this.last_name = CommonTools.filteDangerString(last_name);
        }
        
        if(this.email == null || this.email.trim().length() == 0)
        {
            errors.add("email", new ActionMessage("enquiry.no.email.error"));
        }
        else if(this.email.trim().length() > 100)
        {
            errors.add("email", new ActionMessage("enquiry.email.too.long.error"));
        }
        else
        {
            this.email = CommonTools.filteDangerString(email);
            
            if(!CommonTools.isEMailValid(email))
            {
                errors.add("email", new ActionMessage("enquiry.email.format.error"));
            }
        }
                
        if(this.enquiry == null || this.enquiry.trim().length() == 0)
        {
            errors.add("enquiry", new ActionMessage("enquiry.no.enquiry.error"));
        }
        else if(this.enquiry.trim().length() > 100)
        {
            errors.add("enquiry", new ActionMessage("enquiry.too.long.error"));
        }
        else
        {
            this.enquiry = CommonTools.filteDangerString(enquiry);
        }
        
        if(this.security_code == null || this.security_code.trim().length() == 0)
        {
            errors.add("security_code", new ActionMessage("enquiry.no.securitycode.error"));
        }
        else if(this.security_code.trim().length() > 100)
        {
            errors.add("security_code", new ActionMessage("enquiry.securitycode.too.long.error"));
        }
        else
        {
            this.security_code = CommonTools.filteDangerString(security_code);
        }
        
        return errors; 
    }

    /** 
     * Method reset
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request)
    {
        // TODO Auto-generated method stub
    }
}
