/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cleartraders.webapp.controller.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.cleartraders.common.util.tools.CommonTools;

/** 
 * MyEclipse Struts
 * Creation date: 09-29-2008
 * 
 * XDoclet definition:
 * @struts.form name="selectMarketForm"
 */
public class SelectMarketForm extends ActionForm
{
    private static final long serialVersionUID = -1907654287351095450L;

    /** update_result property */
    private String update_result;

    /** current_market_id property */
    private String current_market_id;

    /*
     * Generated Methods
     */

    /** 
     * Method validate
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping,
            HttpServletRequest request)
    {
        if(update_result != null)
        {
            update_result = CommonTools.filteDangerString(update_result);
        }
        
        if(current_market_id != null)
        {
            current_market_id = CommonTools.filteDangerString(current_market_id);
        }
        
        return null;
    }

    /** 
     * Method reset
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request)
    {
        // TODO Auto-generated method stub
    }

    /** 
     * Returns the update_result.
     * @return String
     */
    public String getUpdate_result()
    {
        return update_result;
    }

    /** 
     * Set the update_result.
     * @param update_result The update_result to set
     */
    public void setUpdate_result(String update_result)
    {
        this.update_result = update_result;
    }

    /** 
     * Returns the current_market_id.
     * @return String
     */
    public String getCurrent_market_id()
    {
        return current_market_id;
    }

    /** 
     * Set the current_market_id.
     * @param current_market_id The current_market_id to set
     */
    public void setCurrent_market_id(String current_market_id)
    {
        this.current_market_id = current_market_id;
    }
}
