/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cleartraders.webapp.controller.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 05-05-2010
 * 
 * XDoclet definition:
 * @struts.form name="sortSignalForm"
 */
public class SortSignalForm extends ActionForm
{
    private static final long serialVersionUID = 1L;
    
    /** sort_type property */
    private String sort_type_id;

    /*
     * Generated Methods
     */

    /** 
     * Method validate
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping, HttpServletRequest request)
    {
        // TODO Auto-generated method stub
        return null;
    }

    /** 
     * Method reset
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request)
    {
        // TODO Auto-generated method stub
    }

    /** 
     * Returns the sort_type.
     * @return String
     */
    public String getSort_type_id()
    {
        return sort_type_id;
    }

    /** 
     * Set the sort_type.
     * @param sort_type The sort_type to set
     */
    public void setSort_type_id(String sort_type_id)
    {
        this.sort_type_id = sort_type_id;
    }
}
