/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cleartraders.webapp.controller.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

import com.cleartraders.common.util.tools.CommonTools;

/** 
 * MyEclipse Struts
 * Creation date: 03-08-2009
 * 
 * XDoclet definition:
 * @struts.form name="tellAFriendForm"
 */
public class TellAFriendForm extends ActionForm
{
    /*
     * Generated Methods
     */

    /**
     * 
     */
    private static final long serialVersionUID = -3114587511238069143L;
    
    private String sender_name = "";
    private String sender_email = "";
    private String receiver_name_1 = "";
    private String receiver_email_1 = "";
    private String receiver_name_2 = "";
    private String receiver_email_2 = "";

    public String getReceiver_email_1()
    {
        return receiver_email_1;
    }

    public void setReceiver_email_1(String receiver_email_1)
    {
        this.receiver_email_1 = receiver_email_1;
    }

    public String getReceiver_email_2()
    {
        return receiver_email_2;
    }

    public void setReceiver_email_2(String receiver_email_2)
    {
        this.receiver_email_2 = receiver_email_2;
    }

    public String getReceiver_name_1()
    {
        return receiver_name_1;
    }

    public void setReceiver_name_1(String receiver_name_1)
    {
        this.receiver_name_1 = receiver_name_1;
    }

    public String getReceiver_name_2()
    {
        return receiver_name_2;
    }

    public void setReceiver_name_2(String receiver_name_2)
    {
        this.receiver_name_2 = receiver_name_2;
    }

    public String getSender_email()
    {
        return sender_email;
    }

    public void setSender_email(String sender_email)
    {
        this.sender_email = sender_email;
    }

    public String getSender_name()
    {
        return sender_name;
    }

    public void setSender_name(String sender_name)
    {
        this.sender_name = sender_name;
    }

    /** 
     * Method validate
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping,
            HttpServletRequest request)
    {
        ActionErrors errors = new ActionErrors();
        
        if(this.sender_name == null || this.sender_name.trim().length() == 0 )
        {
            errors.add("sender_name", new ActionMessage("tellafriend.no.sender.name.error"));
        }
        else if(this.sender_name.trim().length() > 100)
        {
            errors.add("sender_name", new ActionMessage("tellafriend.sender.name.too.long.error"));
        }
        else
        {
            sender_name = CommonTools.filteDangerString(sender_name);
        }
        
        if(this.sender_email == null || this.sender_email.trim().length() == 0)
        {
            errors.add("sender_email", new ActionMessage("tellafriend.no.sender.email.error"));
        }
        else if(this.sender_email.trim().length() > 100)
        {
            errors.add("sender_email", new ActionMessage("tellafriend.sender.email.too.long.error"));
        }
        else
        {
            this.sender_email = CommonTools.filteDangerString(sender_email);
            
            if(!CommonTools.isEMailValid(sender_email))
            {
                errors.add("sender_email", new ActionMessage("tellafriend.sender.email.format.error"));
            }
        }
        
        if(this.receiver_name_1 == null || this.receiver_name_1.trim().length() == 0)
        {
            errors.add("receiver_name_1", new ActionMessage("tellafriend.no.receiver.name1.error"));
        }
        else if(this.receiver_name_1.trim().length() > 100)
        {
            errors.add("receiver_name_1", new ActionMessage("tellafriend.receiver.name1.too.long.error"));
        }
        else
        {
            this.receiver_name_1 = CommonTools.filteDangerString(receiver_name_1);
        }
        
        if(this.receiver_email_1 == null || this.receiver_email_1.trim().length() == 0)
        {
            errors.add("receiver_email_1", new ActionMessage("tellafriend.no.receiver.email.error"));
        }
        else if(this.receiver_email_1.trim().length() > 100)
        {
            errors.add("receiver_email_1", new ActionMessage("tellafriend.receiver.email.too.long.error"));
        }
        else
        {
            this.receiver_email_1 = CommonTools.filteDangerString(receiver_email_1);
            
            if(!CommonTools.isEMailValid(receiver_email_1))
            {
                errors.add("receiver_email_1", new ActionMessage("tellafriend.receiver.email.format.error"));
            }
        }
                
        if(this.receiver_name_2 == null || this.receiver_name_2.trim().length() == 0)
        {
            errors.add("receiver_name_2", new ActionMessage("tellafriend.no.receiver.name2.error"));
        }
        else if(this.receiver_name_2.trim().length() > 100)
        {
            errors.add("receiver_name_2", new ActionMessage("tellafriend.receiver.name2.too.long.error"));
        }
        else
        {
            this.receiver_name_2 = CommonTools.filteDangerString(receiver_name_2);
        }
        
        if(this.receiver_email_2 == null || this.receiver_email_2.trim().length() == 0)
        {
            errors.add("receiver_email_2", new ActionMessage("tellafriend.no.receiver.emai2.error"));
        }
        else if(this.receiver_email_2.trim().length() > 100)
        {
            errors.add("receiver_email_2", new ActionMessage("tellafriend.receiver.emai2.too.long.error"));
        }
        else
        {
            this.receiver_email_2 = CommonTools.filteDangerString(receiver_email_2);
            
            if(!CommonTools.isEMailValid(receiver_email_2))
            {
                errors.add("receiver_email_2", new ActionMessage("tellafriend.receiver.emai2.format.error"));
            }
        }
        
        return errors; 
    }

    /** 
     * Method reset
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request)
    {
        // TODO Auto-generated method stub
    }
}
