/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cleartraders.webapp.controller.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.cleartraders.common.util.tools.CommonTools;

/** 
 * MyEclipse Struts
 * Creation date: 09-27-2008
 * 
 * XDoclet definition:
 * @struts.form name="UpdateTradingPreferenceForm"
 */
public class UpdateTradingPreperenceForm extends ActionForm
{
    /*
     * Generated fields
     */

    /**
     * 
     */
    private static final long serialVersionUID = 2949696216058433263L;

    /** mobile_number property */
    private String mobile_number;

    /** email_address property */
    private String email_address;
    
    private String time_zone;
    
    private String broker_fee;
    
    private String use_conact_info_flag;
    
    //for news
    private String news_name_1;
    private String news_name_2;
    private String news_name_3;
    private String news_url_1;
    private String news_url_2;
    private String news_url_3;
    
    //for broker
    private String broker_name_1;
    private String broker_name_2;
    private String broker_name_3;
    private String broker_url_1;
    private String broker_url_2;
    private String broker_url_3;

    /*
     * Generated Methods
     */


    public String getBroker_fee()
    {
        return broker_fee;
    }

    public void setBroker_fee(String broker_fee)
    {
        this.broker_fee = broker_fee;
    }

    public String getBroker_name_1()
    {
        return broker_name_1;
    }

    public void setBroker_name_1(String broker_name_1)
    {
        this.broker_name_1 = broker_name_1;
    }

    public String getBroker_name_2()
    {
        return broker_name_2;
    }

    public void setBroker_name_2(String broker_name_2)
    {
        this.broker_name_2 = broker_name_2;
    }

    public String getBroker_name_3()
    {
        return broker_name_3;
    }

    public void setBroker_name_3(String broker_name_3)
    {
        this.broker_name_3 = broker_name_3;
    }

    public String getBroker_url_1()
    {
        return broker_url_1;
    }

    public void setBroker_url_1(String broker_url_1)
    {
        this.broker_url_1 = broker_url_1;
    }

    public String getBroker_url_2()
    {
        return broker_url_2;
    }

    public void setBroker_url_2(String broker_url_2)
    {
        this.broker_url_2 = broker_url_2;
    }

    public String getBroker_url_3()
    {
        return broker_url_3;
    }

    public void setBroker_url_3(String broker_url_3)
    {
        this.broker_url_3 = broker_url_3;
    }

    public String getNews_name_1()
    {
        return news_name_1;
    }

    public void setNews_name_1(String news_name_1)
    {
        this.news_name_1 = news_name_1;
    }

    public String getNews_name_2()
    {
        return news_name_2;
    }

    public void setNews_name_2(String news_name_2)
    {
        this.news_name_2 = news_name_2;
    }

    public String getNews_name_3()
    {
        return news_name_3;
    }

    public void setNews_name_3(String news_name_3)
    {
        this.news_name_3 = news_name_3;
    }

    public String getNews_url_1()
    {
        return news_url_1;
    }

    public void setNews_url_1(String news_url_1)
    {
        this.news_url_1 = news_url_1;
    }

    public String getNews_url_2()
    {
        return news_url_2;
    }

    public void setNews_url_2(String news_url_2)
    {
        this.news_url_2 = news_url_2;
    }

    public String getNews_url_3()
    {
        return news_url_3;
    }

    public void setNews_url_3(String news_url_3)
    {
        this.news_url_3 = news_url_3;
    }

    public String getTime_zone()
    {
        return time_zone;
    }

    public void setTime_zone(String time_zone)
    {
        this.time_zone = time_zone;
    }

    /** 
     * Method validate
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping,
            HttpServletRequest request)
    {
        if(mobile_number != null)
        {
            mobile_number = CommonTools.filteDangerString(mobile_number.trim());
        }

        /** email_address property */
        if(email_address != null)
        {
            email_address = CommonTools.filteDangerString(email_address.trim());
        }
        if(time_zone != null)
        {
            time_zone = CommonTools.filteDangerString(time_zone.trim());
        }
        
        if(broker_fee !=null)
        {
            broker_fee = CommonTools.filteDangerString(broker_fee.trim());
        }
        
        if(use_conact_info_flag !=null)
        {
            use_conact_info_flag = CommonTools.filteDangerString(use_conact_info_flag.trim());
        }
        
        //for news
        if(news_name_1 != null)
        {
            news_name_1 = CommonTools.filteDangerString(news_name_1.trim());
        }
        
        if(news_name_2 != null)
        {
            news_name_2 = CommonTools.filteDangerString(news_name_2.trim());
        }
        
        if(news_name_3 != null)
        {
            news_name_3 = CommonTools.filteDangerString(news_name_3.trim());
        }
        
        if(news_url_1 != null)
        {
            news_url_1 = CommonTools.filteDangerString(news_url_1.trim());
        }
        
        if(news_url_2 != null)
        {
            news_url_2 = CommonTools.filteDangerString(news_url_2.trim());
        }
        
        if(news_url_3 != null)
        {
            news_url_3 = CommonTools.filteDangerString(news_url_3.trim());
        }
        
        //for broker
        if(broker_name_1 != null)
        {
            broker_name_1 = CommonTools.filteDangerString(broker_name_1.trim());
        }
        
        if(broker_name_2 != null)
        {
            broker_name_2 = CommonTools.filteDangerString(broker_name_2.trim());
        }
        
        if(broker_name_3 != null)
        {
            broker_name_3 = CommonTools.filteDangerString(broker_name_3.trim());
        }
        
        if(broker_url_1 != null)
        {
            broker_url_1 = CommonTools.filteDangerString(broker_url_1.trim());
        }
        
        if(broker_url_2 != null)
        {
            broker_url_2 = CommonTools.filteDangerString(broker_url_2.trim());
        }
        
        if(broker_url_3 != null)
        {
            broker_url_3 = CommonTools.filteDangerString(broker_url_3.trim());
        }
        
        return null;
    }

    /** 
     * Method reset
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request)
    {
        // TODO Auto-generated method stub
    }

    /** 
     * Returns the mobile_number.
     * @return String
     */
    public String getMobile_number()
    {
        return mobile_number;
    }

    /** 
     * Set the mobile_number.
     * @param mobile_number The mobile_number to set
     */
    public void setMobile_number(String mobile_number)
    {
        this.mobile_number = mobile_number;
    }

    /** 
     * Returns the email_address.
     * @return String
     */
    public String getEmail_address()
    {
        return email_address;
    }

    /** 
     * Set the email_address.
     * @param email_address The email_address to set
     */
    public void setEmail_address(String email_address)
    {
        this.email_address = email_address;
    }

    public String getUse_conact_info_flag()
    {
        return use_conact_info_flag;
    }

    public void setUse_conact_info_flag(String use_conact_info_flag)
    {
        this.use_conact_info_flag = use_conact_info_flag;
    }
}
