/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cleartraders.webapp.controller.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.cleartraders.common.util.tools.CommonTools;

/** 
 * MyEclipse Struts
 * Creation date: 10-26-2008
 * 
 * XDoclet definition:
 * @struts.form name="updateMyAnalysisConditionForm"
 */
public class UpdateMyAnalysisConditionForm extends ActionForm
{
    /*
     * Generated Methods
     */

    /**
     * 
     */
    private static final long serialVersionUID = -2195762777108584713L;

    private String condition_id;
    private String operation_type;
    private String analysis_type;
    
    public String getAnalysis_type()
    {
        return analysis_type;
    }

    public void setAnalysis_type(String analysis_type)
    {
        this.analysis_type = analysis_type;
    }

    public String getCondition_id()
    {
        return condition_id;
    }

    public void setCondition_id(String condition_id)
    {
        this.condition_id = condition_id;
    }

    public String getOperation_type()
    {
        return operation_type;
    }

    public void setOperation_type(String operation_type)
    {
        this.operation_type = operation_type;
    }

    /** 
     * Method validate
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping,
            HttpServletRequest request)
    {
        if(null == analysis_type)
        {
            analysis_type = "-1";
        }
        else
        {
            analysis_type = CommonTools.filteDangerString(analysis_type);
        }
        
        if(null == operation_type)
        {
            operation_type = "-1";
        }
        else
        {
            operation_type = CommonTools.filteDangerString(operation_type);
        }
        
        if(null == condition_id)
        {
            condition_id = "-1";
        }
        else
        {
            condition_id = CommonTools.filteDangerString(condition_id);
        }
        
        return null;
    }

    /** 
     * Method reset
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request)
    {
        // TODO Auto-generated method stub
    }
}
