/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cleartraders.webapp.controller.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

import com.cleartraders.common.util.tools.CommonTools;

/** 
 * MyEclipse Struts
 * Creation date: 09-07-2008
 * 
 * XDoclet definition:
 * @struts.form name="userLoginForm"
 */
public class UserLoginForm extends ActionForm
{
    private static final long serialVersionUID = -6952166700118532879L;

    /** username property */
    private String username;

    /** securitycode property */
//    private String securitycode;

    /** password property */
    private String password;

    /*
     * Generated Methods
     */

    /** 
     * Returns the username.
     * @return String
     */
    public String getUsername()
    {
        return username;
    }

    /** 
     * Set the username.
     * @param username The username to set
     */
    public void setUsername(String username)
    {
        this.username = username;
    }

    /** 
     * Returns the securitycode.
     * @return String
     */
//    public String getSecuritycode()
//    {
//        return securitycode;
//    }

    /** 
     * Set the securitycode.
     * @param securitycode The securitycode to set
     */
//    public void setSecuritycode(String securitycode)
//    {
//        this.securitycode = securitycode;
//    }

    /** 
     * Returns the password.
     * @return String
     */
    public String getPassword()
    {
        return password;
    }

    /** 
     * Set the password.
     * @param password The password to set
     */
    public void setPassword(String password)
    {
        this.password = password;
    }
    
    public ActionErrors validate(ActionMapping actionMapping, HttpServletRequest httpServletRequest)
    {
        ActionErrors errors = new ActionErrors();
        
        if(null == username || username.length() < 1)
        {
            errors.add("username", new ActionMessage("login.no.username.error"));
        }
        else
        {
            username = CommonTools.filteDangerString(username);
        }
        
        if(null == password || password.length() < 1)
        {
            errors.add("password", new ActionMessage("login.no.password.error"));
        }
        else
        {
            password = CommonTools.filteDangerString(password);
        }
        
        //does NOT check security code
        
//        if(null == securitycode || securitycode.length() < 1)
//        {
//            errors.add("securitycode", new ActionMessage("login.no.securitycode.error"));
//        }
//        else
//        {
//            securitycode = CommonTools.filteDangerString(securitycode);
//        }
        
        return errors;
    }
}
