/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cleartraders.webadmin.controller.action;

import java.io.IOException;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Map;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import com.cleartraders.common.entity.StrategyBean;
import com.cleartraders.common.entity.UserBean;
import com.cleartraders.common.entity.UserBeanAToZComparator;
import com.cleartraders.common.util.log.DebugLevel;
import com.cleartraders.common.util.log.LogTools;
import com.cleartraders.common.util.tools.CommonTools;
import com.cleartraders.webadmin.AdminConstants;
import com.cleartraders.webadmin.controller.form.DeleteMemberForm;
import com.cleartraders.webadmin.model.member.MemberController;

/** 
 * MyEclipse Struts
 * Creation date: 03-11-2009
 * 
 * XDoclet definition:
 * @struts.action path="/deleteMember" name="deleteMemberForm" input="/members/members.jsp" scope="request" validate="true"
 */
public class DeleteMemberAction extends BaseAction
{
    @Override
    protected ActionForward executeAction(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
    {
        String forwardName = AdminConstants.FORWARD_FAILED;
        ActionMessages errors = new ActionMessages();
        MemberController memberController = new MemberController();
        
        try
        {
            DeleteMemberForm deleteMemberForm = (DeleteMemberForm) form;// TODO Auto-generated method stub
            
            //for log info
            UserBean currentAdmin = (UserBean)request.getSession().getAttribute(AdminConstants.USER_KEY);
            LogTools.getInstance().insertLog(DebugLevel.INFO,"Request DeleteMemberAction from Account:"+currentAdmin.getLogin_name()+
                    ", Target user account:"+deleteMemberForm.getMember_delete_name());
            
            
            long memberID = Long.parseLong(deleteMemberForm.getMember_delete_id());
            
            if(memberController.deleteMember(memberID, deleteMemberForm.getMember_delete_name()))
            {
                forwardName = AdminConstants.FORWARD_SUCCESS;
                
                LogTools.getInstance().insertLog(DebugLevel.INFO,"Delete member:"+deleteMemberForm.getMember_delete_name()+" successfully!");
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
            
            LogTools.getInstance().insertLog(DebugLevel.ERROR,CommonTools.getExceptionDescribe(e));            
            
            errors.add("error", new ActionMessage("member.delete.request.data.error"));            
            saveErrors(request, errors);
        }
        finally
        {
            List<UserBean> searchResult = memberController.getAllMembers();            
            Comparator<UserBean> comp = new UserBeanAToZComparator();
            Collections.sort(searchResult,comp);            
            request.setAttribute(AdminConstants.MEMBER_LIST, searchResult);
            
            Map<Long, List<StrategyBean>> marketStrategy = new MemberController().getMarketStrategyMap();
            request.setAttribute(AdminConstants.MARKET_STRATEGY_MAP, marketStrategy);
        }
        
        return mapping.findForward(forwardName);
    }
}
