/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cleartraders.webadmin.controller.action;

import java.io.IOException;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Map;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.cleartraders.common.define.CommonDefine;
import com.cleartraders.common.entity.StrategyBean;
import com.cleartraders.common.entity.UserBean;
import com.cleartraders.common.entity.UserBeanAToZComparator;
import com.cleartraders.common.util.log.DebugLevel;
import com.cleartraders.common.util.log.LogTools;
import com.cleartraders.webadmin.AdminConstants;
import com.cleartraders.webadmin.controller.form.SearchMemberForm;
import com.cleartraders.webadmin.model.member.MemberController;

/**
 * MyEclipse Struts Creation date: 03-02-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/searchMember" name="searchMemberForm"
 *                input="/members/members.jsp" scope="request" validate="true"
 */
public class SearchMemberAction extends BaseAction
{
    protected ActionForward executeAction(ActionMapping mapping,
            ActionForm form, HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException
    {
        SearchMemberForm searchMemberForm = (SearchMemberForm) form;
        
        String memberName = searchMemberForm.getSearch_name();
        String memberEmail = searchMemberForm.getSearch_email();
        
        //for log info
        UserBean currentAdmin = (UserBean)request.getSession().getAttribute(AdminConstants.USER_KEY);
        LogTools.getInstance().insertLog(DebugLevel.INFO,"Request SearchMemberAction from Account:"+currentAdmin.getLogin_name()+
                ", search member name:"+memberName+", search email:"+memberEmail);
        
        String forwardName = AdminConstants.FORWARD_SUCCESS;
        
                
        List<UserBean> searchResult = new MemberController().searchMember(memberName, memberEmail, CommonDefine.ALL_MEMBER_TYPE);
        
        Comparator<UserBean> comp = new UserBeanAToZComparator();
        Collections.sort(searchResult,comp);
        
        request.setAttribute(AdminConstants.MEMBER_LIST, searchResult);
        
        Map<Long, List<StrategyBean>> marketStrategy = new MemberController().getMarketStrategyMap();
        request.setAttribute(AdminConstants.MARKET_STRATEGY_MAP, marketStrategy);
        
        return mapping.findForward(forwardName);
    }
}
