/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cleartraders.webapp.controller.action;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.cleartraders.common.entity.UserBean;
import com.cleartraders.common.util.log.DebugLevel;
import com.cleartraders.common.util.log.LogTools;
import com.cleartraders.common.util.tools.CommonTools;
import com.cleartraders.webapp.WebConstants;
import com.cleartraders.webapp.config.WebappResManager;
import com.cleartraders.webapp.controller.form.BuySMSCreditsForm;
import com.cleartraders.webapp.db.DBAccessor;

/** 
 * MyEclipse Struts
 * Creation date: 03-09-2009
 * 
 * XDoclet definition:
 * @struts.action path="/buySMSCredits" name="buySMSCreditsForm" input="/myaccount/smscredits.jsp" scope="request" validate="true"
 */
public class BuySMSCreditsAction extends BaseAction
{
    @Override
    protected ActionForward executeAction(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
    {
        String forwardName = WebConstants.FORWARD_FAILED;
        
        try
        {
            BuySMSCreditsForm buySMSCreditsForm = (BuySMSCreditsForm) form;
            
            HttpSession session = request.getSession();
            
            //Base action already handle logout or timeout issue, so, here we don't need check
            UserBean oUserBean = (UserBean)session.getAttribute(WebConstants.USER_KEY);
            
            LogTools.getInstance().insertLog(DebugLevel.INFO,"BUY SMS Credit request from User:"+oUserBean.getLogin_name()+", IP:"+request.getRemoteAddr()+
                    ", Button ID:"+buySMSCreditsForm.getAlert_credits_package());
            
            String paypalCmd = WebappResManager.getInstance().getPaypal_subscription_cmd();
            String hosted_button_id = DBAccessor.getInstance().getSMSPackageButtonByID(Long.parseLong(buySMSCreditsForm.getAlert_credits_package()));
            
            request.setAttribute("cmd", paypalCmd);
            request.setAttribute("hosted_button_id", hosted_button_id);
            
            //use Email as custom name to verify
            request.setAttribute("custom", oUserBean.getLogin_name());
            
            forwardName = "successful_paid";
            
            LogTools.getInstance().insertLog(DebugLevel.INFO,"Send request of BUY SMS Credit to Paypal for User:"+oUserBean.getLogin_name()+", from IP:"+request.getRemoteAddr()+
                    ", Button ID:"+buySMSCreditsForm.getAlert_credits_package());
        }
        catch(Exception e)
        {
            e.printStackTrace();
            
            LogTools.getInstance().insertLog(DebugLevel.ERROR,CommonTools.getExceptionDescribe(e));
        }
        
        return mapping.findForward(forwardName);
    }
}
