/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cleartraders.webapp.controller.action;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.cleartraders.common.entity.UserBean;
import com.cleartraders.webapp.WebConstants;
import com.cleartraders.webapp.controller.form.ChangeAlertForm;
import com.cleartraders.webapp.model.myaccount.AccountController;

/** 
 * MyEclipse Struts
 * Creation date: 04-04-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ChangeAlertAction extends BaseAction
{
    @Override
    protected ActionForward executeAction(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
    {
        try
        {
            ChangeAlertForm changeAlertForm = (ChangeAlertForm) form;
            
            HttpSession session = request.getSession();
            
            //Base action already handle logout or timeout issue, so, here we don't need check
            UserBean oCurrentUserInfo = (UserBean)session.getAttribute(WebConstants.USER_KEY);
            
            AccountController accountController = new AccountController();
            accountController.updateSignalAlertType(oCurrentUserInfo,                                                     
                                                    Long.parseLong(changeAlertForm.getMarket_id()),
                                                    Long.parseLong(changeAlertForm.getPeriod_id()),
                                                    Long.parseLong(changeAlertForm.getStrategy_id()),
                                                    Integer.parseInt(changeAlertForm.getAlert_type()));
                        
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
        return null;
    }
}
