/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cleartraders.webapp.controller.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.cleartraders.common.db.DataCache;
import com.cleartraders.common.entity.UserBean;
import com.cleartraders.webapp.WebConstants;
import com.cleartraders.webapp.model.myaccount.AccountController;

/** 
 * MyEclipse Struts
 * Creation date: 09-23-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="sessionended" path="/login/userLogin.jsp"
 * @struts.action-forward name="successful" path="/myaccount/contacts.jsp"
 */
public class GetContactsAction extends BaseAction
{
    /*
     * Generated Methods
     */

    /** 
     * Method execute
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward executeAction(ActionMapping mapping, ActionForm form,
            HttpServletRequest request, HttpServletResponse response)
    {
        //System can get Contacts Info from Session, So this Action will be used in the future for other requirement
        request.setAttribute(WebConstants.ALL_COUNTRY_DATA, DataCache.getInstance().getAllCountry());
        
        HttpSession session = request.getSession();
        
        //Base action already handle logout or timeout issue, so, here we don't need check
        UserBean oUserBean = (UserBean)session.getAttribute(WebConstants.USER_KEY);
        
        //get all trading time zone
        request.setAttribute(WebConstants.USER_TRADING_TIME_ZONE, (new AccountController()).getUserTimeZone(oUserBean));
        request.setAttribute(WebConstants.ALL_TIME_ZONE, DataCache.getInstance().getAllTimeZone());
        
        String forward = WebConstants.FORWARD_SUCCESS;
        
        return mapping.findForward(forward);
    }
}
