/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cleartraders.webapp.controller.action;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.cleartraders.common.entity.UserBean;
import com.cleartraders.common.util.log.DebugLevel;
import com.cleartraders.common.util.log.LogTools;
import com.cleartraders.common.util.tools.CommonTools;
import com.cleartraders.webapp.WebConstants;
import com.cleartraders.webapp.model.activesignals.ActiveSignalsList;

/** 
 * MyEclipse Struts
 * Creation date: 05-08-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class GetLatestTimeframeSignalsAction extends BaseAction
{

    @Override
    protected ActionForward executeAction(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
    {
        response.setContentType("text/xml");
        response.setCharacterEncoding("UTF-8");
        response.setHeader("Charset","UTF-8");
        
        ActiveSignalsList signalController = new ActiveSignalsList();
        
        String strategyIDPara = (String)request.getParameter("strategyid");
        String marketIDPara = (String)request.getParameter("marketid");
        
        if(null == strategyIDPara || null == marketIDPara)
        {
            return null;
        }
        
        try
        {            
            long strategyID = Long.parseLong(strategyIDPara);
            long marketID = Long.parseLong(marketIDPara);
            
            //for log info
            UserBean currentUser = (UserBean)request.getSession().getAttribute(WebConstants.USER_KEY);
            
            LogTools.getInstance().insertLog(DebugLevel.INFO,"Request GetLatestTimeframeSignalsAction from Account:"+currentUser.getLogin_name()+ ", strategy id:"+strategyID+", market id:"+marketID);
            
            long userTimeOffset = getUserOffsetTime(request);
            String result = signalController.getLastestTimeframeSignals(strategyID, marketID, userTimeOffset);
                    
            response.getWriter().println(result);        
        }
        catch (Exception e)
        {
            e.printStackTrace();
            
            LogTools.getInstance().insertLog(DebugLevel.ERROR,CommonTools.getExceptionDescribe(e)); 
        }
        
        return null;
    }
}
