/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cleartraders.webapp.controller.action;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.cleartraders.common.entity.StrategyBean;
import com.cleartraders.common.entity.UserBean;
import com.cleartraders.common.util.log.DebugLevel;
import com.cleartraders.common.util.log.LogTools;
import com.cleartraders.common.util.tools.CommonTools;
import com.cleartraders.webapp.WebConstants;
import com.cleartraders.webapp.model.myaccount.AccountController;

/** 
 * MyEclipse Struts
 * Creation date: 05-05-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class GetStrategyByIDAction extends BaseAction
{
    protected ActionForward executeAction(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
    {
        AccountController accountController = new AccountController();
        
        response.setContentType("text/xml");
        response.setCharacterEncoding("UTF-8");
        response.setHeader("Charset","UTF-8");
        
        String strategyIDPara = (String)request.getParameter("id");
        
        if(null == strategyIDPara)
        {
            return null;
        }
        
        try
        {
            long strategyID = Long.parseLong(strategyIDPara);
            
            StrategyBean strategyBean = accountController.getStrategyByID(strategyID);
            
            //for log info
            UserBean currentUser = (UserBean)request.getSession().getAttribute(WebConstants.USER_KEY);
            
            LogTools.getInstance().insertLog(DebugLevel.INFO,"Request GetStrategyByIDAction from Account:"+currentUser.getLogin_name()+
                    ", strategy name:"+strategyBean.getSystem_name());
            
            String result = strategyBean.getDescriptionString();
            
            //result += ";markets="+memberController.getMemberSubcribleMarketString(strategyID);
            
            response.getWriter().println(result);
        }
        catch (Exception e)
        {
            e.printStackTrace();
            
            LogTools.getInstance().insertLog(DebugLevel.ERROR,CommonTools.getExceptionDescribe(e)); 
        }
        
        return null;
    }
}
