/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cleartraders.webapp.controller.action;

import java.io.PrintWriter;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.cleartraders.common.util.log.DebugLevel;
import com.cleartraders.common.util.log.LogTools;
import com.cleartraders.common.util.tools.CommonTools;
import com.cleartraders.webapp.model.analysis.AnalysisController;
import com.cleartraders.webapp.model.bean.TradeBean;

/** 
 * MyEclipse Struts
 * Creation date: 09-01-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class GetTop20TradeAction extends Action
{
    /*
     * Generated Methods
     */

    /** 
     * Method execute
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request,
            HttpServletResponse response)
    {
        try
        {
            LogTools.getInstance().insertLog(DebugLevel.INFO, "Get Top 20 Trades from IP:" + request.getRemoteAddr());

            String top20Trades = "";
            
            List<TradeBean> oTop20Trades = (new AnalysisController()).getTopProfitTrade(20);
            if(null != oTop20Trades)
            {
                for(int i=0; i<oTop20Trades.size(); i++)
                {
                    TradeBean oTrade = oTop20Trades.get(i);
                    top20Trades += oTrade.toTextMessage();
                    
                    if(i < (oTop20Trades.size() - 1))
                    {
                        top20Trades += ";";
                    }
                }
            }
            
            PrintWriter out = new PrintWriter(response.getOutputStream());

            out.write(top20Trades);
            out.flush();
            out.close();
        }
        catch (Exception e)
        {
            e.printStackTrace();

            LogTools.getInstance().insertLog(DebugLevel.ERROR, CommonTools.getExceptionDescribe(e));
        }

        return null;
    }
}
