/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cleartraders.webapp.controller.action;

import java.net.URLDecoder;
import java.util.Enumeration;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.cleartraders.common.util.log.DebugLevel;
import com.cleartraders.common.util.log.LogTools;
import com.cleartraders.webapp.model.payment.PaymentIPNController;

/** 
 * MyEclipse Struts
 * Creation date: 02-12-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class PaypalIPNCallbackAction extends Action
{
    /*
     * Generated Methods
     */

    /** 
     * Method execute
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward execute(ActionMapping mapping, ActionForm form,
            HttpServletRequest request, HttpServletResponse response)
    {
        Enumeration allParameters = request.getParameterNames();
        
        LogTools.getInstance().insertLog(DebugLevel.INFO,"Show parameters from Paypal IPN notification ---------------------------------------");
        
        while(allParameters.hasMoreElements())
        {
            try
            {
                String paramName = (String)allParameters.nextElement();
                String paramValue = URLDecoder.decode(request.getParameter(paramName), "UTF-8");
                
                LogTools.getInstance().insertLog(DebugLevel.INFO,"Parameter Key:"+paramName+", Value:"+paramValue);
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
        }
        
        LogTools.getInstance().insertLog(DebugLevel.INFO,"End Show parameters from Paypal IPN notification ---------------------------------------");
                
        new PaymentIPNController().handlePaypalIPNNotification(request, response);
               
        return null;
    }
}
