/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cleartraders.webapp.controller.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.cleartraders.common.db.DataCache;
import com.cleartraders.common.util.log.DebugLevel;
import com.cleartraders.common.util.log.LogTools;

/** 
 * MyEclipse Struts
 * Creation date: 02-05-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ReloadDataCacheAction extends Action
{
    /*
     * Generated Methods
     */

    /** 
     * Method execute
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward execute(ActionMapping mapping, ActionForm form,
            HttpServletRequest request, HttpServletResponse response)
    {
        LogTools.getInstance().insertLog(DebugLevel.WARNING,"Request to reload Data Cache from IP:"+request.getRemoteAddr());
        
        String checkID = (String)request.getParameter("checkid");
            
        if(null != checkID && checkID.equals("test12*&"))
        {
            DataCache.getInstance().reloadDataCache();
        }
        
        return null;
    }
}
