/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cleartraders.webapp.controller.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.cleartraders.common.entity.UserBean;
import com.cleartraders.common.util.log.DebugLevel;
import com.cleartraders.common.util.log.LogTools;
import com.cleartraders.webapp.WebConstants;

/** 
 * MyEclipse Struts
 * Creation date: 09-08-2008
 * 
 * XDoclet definition:
 * @struts.action input="/signals.jsp" scope="request" validate="true"
 * @struts.action-forward name="successful" path="/logoutCache.jsp"
 */
public class UserLogoffAction extends Action
{
    /** 
     * Method execute
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward execute(ActionMapping mapping, ActionForm form,
            HttpServletRequest request, HttpServletResponse response)
    {        
        HttpSession session = request.getSession();
        UserBean oUserBean = (UserBean)session.getAttribute(WebConstants.USER_KEY);
        
        if(null != oUserBean)
        {
            LogTools.getInstance().insertLog(DebugLevel.INFO,"Logout request from User:"+oUserBean.getLogin_name()+", IP:"+request.getRemoteAddr());
        }
        else
        {
            LogTools.getInstance().insertLog(DebugLevel.INFO,"Session already time out. Logout request from IP:"+request.getRemoteAddr());
        }
        
        session.removeAttribute(WebConstants.USER_KEY);
        session.invalidate();
        
        return mapping.findForward(WebConstants.FORWARD_SUCCESS);
    }
}
